from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Protocol

from rflp_lite.domain.models import (
    Artifact,
    Baseline,
    Candidate,
    Claim,
    Evidence,
    ModelElement,
    Relation,
    SimulationRun,
    TaskContract,
    TextSpan,
)


class RepositoryPort(Protocol):
    def transaction(self) -> AbstractContextManager[None]: ...
    def save_artifacts(self, values: tuple[Artifact, ...]) -> None: ...
    def save_spans(self, values: tuple[TextSpan, ...]) -> None: ...
    def save_claims(self, values: tuple[Claim, ...]) -> None: ...
    def save_elements(self, values: tuple[ModelElement, ...]) -> None: ...
    def save_relations(self, values: tuple[Relation, ...]) -> None: ...
    def save_candidates(self, values: tuple[Candidate, ...]) -> None: ...
    def save_simulation(self, value: SimulationRun) -> None: ...
    def save_baseline(self, value: Baseline) -> Baseline: ...
    def save_tasks(self, values: tuple[TaskContract, ...]) -> None: ...
    def save_evidence(self, values: tuple[Evidence, ...]) -> None: ...
    def latest_baseline(self) -> Baseline | None: ...
    def record_audit(self, kind: str, payload: dict[str, object]) -> int: ...


class SolverPort(Protocol):
    def solve(
        self, elements: tuple[ModelElement, ...], profile: object
    ) -> tuple[Candidate, ...]: ...
